import type { CredentialValidators, ProviderExecutors } from "../core/types.ts";

/** Lazy-loaded provider executor module shape. */
export type ExecutorModule = {
  credentialValidators?: CredentialValidators;
  executors: ProviderExecutors;
};

/** Generated lazy imports for provider executors. Do not hand-edit. */
export const executorModules: Record<string, () => Promise<ExecutorModule>> = {
  github: (): Promise<ExecutorModule> => import("./github/executors.ts"),
  gmail: (): Promise<ExecutorModule> => import("./gmail/executors.ts"),
  hackernews: (): Promise<ExecutorModule> => import("./hackernews/executors.ts"),
  notion: (): Promise<ExecutorModule> => import("./notion/executors.ts"),
};

/** Generated local executable action ids by provider. Do not hand-edit. */
export const executableActionIds: Record<string, string[]> = {
  github: [
    "github.add_issue_assignees",
    "github.add_issue_labels",
    "github.check_pull_request_merged",
    "github.clear_issue_labels",
    "github.compare_commits",
    "github.create_commit_status",
    "github.create_issue",
    "github.create_issue_comment",
    "github.create_label",
    "github.create_or_update_file",
    "github.create_pull_request",
    "github.create_pull_request_review",
    "github.create_pull_request_review_comment",
    "github.create_ref",
    "github.create_release",
    "github.create_repository",
    "github.delete_file",
    "github.delete_repository",
    "github.get_branch",
    "github.get_commit",
    "github.get_commit_statuses",
    "github.get_current_user",
    "github.get_file_contents",
    "github.get_issue",
    "github.get_latest_release",
    "github.get_pull_request",
    "github.get_release",
    "github.get_release_by_tag",
    "github.get_repository",
    "github.get_workflow_run",
    "github.list_authenticated_user_events",
    "github.list_authenticated_user_received_events",
    "github.list_branches",
    "github.list_check_runs_for_ref",
    "github.list_commits",
    "github.list_directory_contents",
    "github.list_issue_comments",
    "github.list_issue_events",
    "github.list_issue_labels",
    "github.list_issue_timeline_events",
    "github.list_my_repositories",
    "github.list_public_events",
    "github.list_pull_request_commits",
    "github.list_pull_request_files",
    "github.list_pull_request_requested_reviewers",
    "github.list_pull_request_review_comments",
    "github.list_pull_request_reviews",
    "github.list_pull_requests",
    "github.list_pull_requests_associated_with_commit",
    "github.list_release_assets",
    "github.list_releases",
    "github.list_repository_events",
    "github.list_repository_issue_events",
    "github.list_repository_issues",
    "github.list_repository_labels",
    "github.list_repository_workflows",
    "github.list_user_public_events",
    "github.list_user_received_public_events",
    "github.list_workflow_run_jobs",
    "github.list_workflow_runs",
    "github.lock_issue",
    "github.merge_branch",
    "github.merge_pull_request",
    "github.remove_issue_assignees",
    "github.remove_issue_label",
    "github.remove_pull_request_reviewers",
    "github.rename_branch",
    "github.reply_pull_request_review_comment",
    "github.request_pull_request_reviewers",
    "github.rerequest_check_run",
    "github.rerequest_check_suite",
    "github.rerun_workflow",
    "github.search_code",
    "github.search_commits",
    "github.search_issues_and_pull_requests",
    "github.search_labels",
    "github.search_repositories",
    "github.search_topics",
    "github.search_users",
    "github.set_issue_labels",
    "github.submit_pull_request_review",
    "github.sync_fork_branch_with_upstream",
    "github.unlock_issue",
    "github.update_issue",
    "github.update_pull_request",
    "github.update_pull_request_branch",
  ],
  gmail: [
    "gmail.add_label_to_email",
    "gmail.batch_modify_messages",
    "gmail.create_draft",
    "gmail.create_email_draft",
    "gmail.create_filter",
    "gmail.create_label",
    "gmail.delete_draft",
    "gmail.delete_filter",
    "gmail.delete_label",
    "gmail.fetch_emails",
    "gmail.fetch_message_by_message_id",
    "gmail.fetch_message_by_thread_id",
    "gmail.get_auto_forwarding",
    "gmail.get_draft",
    "gmail.get_filter",
    "gmail.get_label",
    "gmail.get_language_settings",
    "gmail.get_message",
    "gmail.get_profile",
    "gmail.get_vacation_settings",
    "gmail.list_drafts",
    "gmail.list_filters",
    "gmail.list_forwarding_addresses",
    "gmail.list_history",
    "gmail.list_labels",
    "gmail.list_threads",
    "gmail.modify_thread_labels",
    "gmail.move_thread_to_trash",
    "gmail.move_to_trash",
    "gmail.patch_label",
    "gmail.reply_email",
    "gmail.reply_to_thread",
    "gmail.search_threads",
    "gmail.send_draft",
    "gmail.send_email",
    "gmail.settings_get_imap",
    "gmail.settings_get_pop",
    "gmail.stop_watch",
    "gmail.untrash_message",
    "gmail.untrash_thread",
    "gmail.update_draft",
    "gmail.update_imap_settings",
    "gmail.update_label",
    "gmail.update_language_settings",
    "gmail.update_pop_settings",
    "gmail.update_vacation_settings",
  ],
  hackernews: [
    "hackernews.get_ask_stories",
    "hackernews.get_best_stories",
    "hackernews.get_item",
    "hackernews.get_item_with_id",
    "hackernews.get_job_stories",
    "hackernews.get_latest_posts",
    "hackernews.get_max_item_id",
    "hackernews.get_new_stories",
    "hackernews.get_show_stories",
    "hackernews.get_top_stories",
    "hackernews.get_updates",
    "hackernews.get_user",
    "hackernews.get_user_by_username",
    "hackernews.search_posts",
  ],
  notion: [
    "notion.append_block",
    "notion.append_block_children",
    "notion.create_data_source",
    "notion.create_database",
    "notion.create_page",
    "notion.delete_block",
    "notion.get_page",
    "notion.list_block_children",
    "notion.list_data_source_templates",
    "notion.list_users",
    "notion.move_page",
    "notion.query_data_source",
    "notion.retrieve_block",
    "notion.retrieve_data_source",
    "notion.retrieve_database",
    "notion.retrieve_page",
    "notion.retrieve_page_markdown",
    "notion.retrieve_page_property",
    "notion.retrieve_user",
    "notion.search",
    "notion.update_block",
    "notion.update_data_source",
    "notion.update_database",
    "notion.update_page",
    "notion.update_page_markdown",
  ],
};
