export const feishuAppBotScopes = {
  resource: "im:resource",
  sendMessage: "im:message:send_as_bot",
  readMessage: "im:message:readonly",
  recallMessage: "im:message:recall",
  updateMessage: "im:message:update",
  groupMessage: "im:message.group_msg",
  chatRead: "im:chat:read",
  chatMembersRead: "im:chat.members:read",
  reactionRead: "im:message.reactions:read",
  reactionWrite: "im:message.reactions:write_only",
  pinRead: "im:message.pins:read",
  pinWrite: "im:message.pins:write_only",
  p2pReadonly: "im:message.p2p_msg:readonly",
  groupAtReadonly: "im:message.group_at_msg:readonly",
  groupAtWithBotReadonly: "im:message.group_at_msg.include_bot:readonly",
  groupReadonly: "im:message.group_msg:readonly",
} as const;

export const feishuAppBotProviderScopes: string[] = [
  feishuAppBotScopes.resource,
  feishuAppBotScopes.sendMessage,
  feishuAppBotScopes.readMessage,
  feishuAppBotScopes.recallMessage,
  feishuAppBotScopes.updateMessage,
  feishuAppBotScopes.chatRead,
  feishuAppBotScopes.chatMembersRead,
  feishuAppBotScopes.reactionRead,
  feishuAppBotScopes.reactionWrite,
  feishuAppBotScopes.pinRead,
  feishuAppBotScopes.pinWrite,
  feishuAppBotScopes.p2pReadonly,
  feishuAppBotScopes.groupAtReadonly,
  feishuAppBotScopes.groupAtWithBotReadonly,
  feishuAppBotScopes.groupMessage,
  feishuAppBotScopes.groupReadonly,
];
